BEGIN;
CREATE TEMP TABLE fee_module_checks(name text,passed boolean);
CREATE TEMP TABLE fee_module_context(uid uuid,sid uuid,account uuid);
DO $$
DECLARE staff uuid; uid uuid:=gen_random_uuid(); sid uuid; c record; registration jsonb; admission uuid; monthly uuid; pay jsonb; void_id uuid; data jsonb; generated jsonb; denied boolean; q uuid; pma uuid; afns uuid; count_before int;
BEGIN
 SELECT id INTO staff FROM profiles WHERE role='ADMIN' AND status='ACTIVE' LIMIT 1;
 SELECT * INTO c FROM courses WHERE code='AFNS';SELECT id INTO pma FROM courses WHERE code='PMA_LONG_COURSE';afns:=c.id;
 INSERT INTO auth.users(id,email) VALUES(uid,uid||'@fees-rollback.invalid');
 PERFORM set_config('request.jwt.claim.sub',staff::text,true);PERFORM set_config('request.jwt.claim.role','service_role',true);
 registration:=portal_register_student(uid,staff,jsonb_build_object('email',uid||'@fees-rollback.invalid','fullName','Fee rollback fixture','fatherName','Fixture','cnic','988'||right(replace(uid::text,'-',''),10),'phone','03001234567','targetForceId',c.force_id,'targetCourseId',c.id,'rollNumber','QA-FEE-'||uid,'education','Intermediate','gender','Female','courseFeeAmount',10000,'initialPaymentAmount',2000,'paymentMethod','CASH'));
 sid:=(registration->>'studentId')::uuid;
 PERFORM set_config('request.jwt.claim.role','authenticated',true);
 SELECT id INTO admission FROM student_fee_accounts WHERE student_id=sid AND fee_type='ADMISSION & TUITION FEE';
 IF (SELECT amount_paid FROM student_fee_accounts WHERE id=admission)<>2000 THEN RAISE EXCEPTION 'Registration did not reconcile initial payment'; END IF;
 INSERT INTO fee_module_checks VALUES('Registration account and initial receipt reconcile atomically',true);
 generated:=generate_monthly_fees(10,2026,'October 2026','MONTHLY',1000,NULL,c.force_id,c.id,NULL);
 SELECT id INTO monthly FROM student_fee_accounts WHERE student_id=sid AND fee_type='MONTHLY' AND fee_month=10 AND fee_year=2026;
 IF monthly IS NULL THEN RAISE EXCEPTION 'Monthly fee missing'; END IF;
 generated:=generate_monthly_fees(10,2026,'October 2026','MONTHLY',1000,NULL,c.force_id,c.id,NULL);
 IF (generated->>'created_count')::int<>0 THEN RAISE EXCEPTION 'Monthly fee duplicate'; END IF;
 INSERT INTO fee_module_checks VALUES('Monthly generation is idempotent and includes newly registered eligible students',true);
 pay:=record_student_fee_payment(sid,admission,1000,'CASH',NULL,'Rollback verification');
 PERFORM update_student_fee_adjustment(monthly,100,50,'Verified adjustment');
 pay:=record_student_fee_payment(sid,monthly,950,'CASH',NULL,'Rollback full monthly payment');void_id:=(pay->>'payment_id')::uuid;
 data:=finance_student_fee_data(sid);
 IF (data#>>'{totals,total_fee}')::numeric<>10950 OR (data#>>'{totals,paid_fee}')::numeric<>3950 OR (data#>>'{totals,remaining_fee}')::numeric<>7000 THEN RAISE EXCEPTION 'Fee ledger total mismatch'; END IF;
 INSERT INTO fee_module_checks VALUES('Partial/full payments, discount and fine produce exact ledger totals',true);
 PERFORM waive_student_fee(admission,'Rollback waiver');PERFORM void_student_fee_payment(void_id,'Rollback correction');
 data:=finance_student_fee_data(sid);
 IF (data#>>'{totals,total_fee}')::numeric<>3950 OR (data#>>'{totals,paid_fee}')::numeric<>3000 OR (data#>>'{totals,remaining_fee}')::numeric<>950 THEN RAISE EXCEPTION 'Waiver/void totals incorrect'; END IF;
 IF (SELECT status FROM student_fee_accounts WHERE id=admission)<>'WAIVED' THEN RAISE EXCEPTION 'Waiver status lost'; END IF;
 INSERT INTO fee_module_checks VALUES('Waiver removes remaining obligation; voided receipt retained and excluded from totals',true);
 denied:=false;BEGIN PERFORM record_student_fee_payment(sid,monthly,951,'CASH');EXCEPTION WHEN OTHERS THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'Overpayment accepted'; END IF;
 denied:=false;BEGIN PERFORM record_student_fee_payment(sid,NULL,1,'CASH');EXCEPTION WHEN OTHERS THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'Unallocated payment accepted'; END IF;
 INSERT INTO fee_module_checks VALUES('Overpayment and missing account rejected by backend',true);
 UPDATE student_fee_accounts SET amount_paid=9999,status='PAID' WHERE id=monthly;
 IF (SELECT amount_paid FROM student_fee_accounts WHERE id=monthly)<>0 OR (SELECT status FROM student_fee_accounts WHERE id=monthly)<>'UNPAID' THEN RAISE EXCEPTION 'Frontend paid/status bypass'; END IF;
 INSERT INTO fee_module_checks VALUES('Direct paid/status edits cannot fabricate collected money',true);
 denied:=false;BEGIN INSERT INTO student_fee_payments(student_id,fee_account_id,amount,payment_method,received_by,receipt_number) SELECT s.id,monthly,1,'CASH',staff,'WRONG-'||gen_random_uuid() FROM students s WHERE s.id<>sid LIMIT 1;EXCEPTION WHEN OTHERS THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'Wrong account owner accepted'; END IF;
 INSERT INTO fee_module_checks VALUES('Payment student/account ownership enforced in DB',true);
 SELECT qx.id INTO q FROM questions qx JOIN subjects sub ON sub.id=qx.subject_id WHERE sub.code='INTELLIGENCE_VERBAL' AND EXISTS(SELECT 1 FROM question_courses WHERE question_id=qx.id AND course_id=afns) AND NOT EXISTS(SELECT 1 FROM question_courses WHERE question_id=qx.id AND course_id=pma) LIMIT 1;
 IF q IS NULL OR NOT exam_question_course_eligible(q,pma) THEN RAISE EXCEPTION 'Shared intelligence bank not available to PMA'; END IF;
 SELECT qx.id INTO q FROM questions qx JOIN subjects sub ON sub.id=qx.subject_id WHERE sub.code LIKE 'ACADEMIC%' AND EXISTS(SELECT 1 FROM question_courses WHERE question_id=qx.id AND course_id=afns) AND NOT EXISTS(SELECT 1 FROM question_courses WHERE question_id=qx.id AND course_id=pma) LIMIT 1;
 IF q IS NULL OR exam_question_course_eligible(q,pma) THEN RAISE EXCEPTION 'AFNS academics leaked to PMA'; END IF;
 INSERT INTO question_courses(question_id,course_id) VALUES(q,pma);
 IF exam_question_course_eligible(q,pma) OR exam_question_course_eligible(q,afns) THEN RAISE EXCEPTION 'Academic bank became shared by adding a second mapping'; END IF;
 DELETE FROM question_courses WHERE question_id=q AND course_id=pma;
 INSERT INTO fee_module_checks VALUES('PMA/AFNS intelligence is shared; academic banks stay isolated even with a forged second mapping',true);
 PERFORM set_config('request.jwt.claim.sub',uid::text,true);
 data:=student_portal_snapshot();IF (data#>>'{fees,total_fee}')::numeric<>3950 OR (data#>>'{fees,paid_fee}')::numeric<>3000 OR (data#>>'{fees,remaining_fee}')::numeric<>950 THEN RAISE EXCEPTION 'Student dashboard differs from finance ledger'; END IF;
 denied:=false;BEGIN PERFORM get_finance_summary();EXCEPTION WHEN OTHERS THEN denied:=true;END;IF NOT denied THEN RAISE EXCEPTION 'Student read admin finances'; END IF;
 denied:=false;BEGIN PERFORM finance_students_fee_overview();EXCEPTION WHEN OTHERS THEN denied:=true;END;IF NOT denied THEN RAISE EXCEPTION 'Student read all fee accounts'; END IF;
 denied:=false;BEGIN PERFORM record_student_fee_payment(sid,monthly,1,'CASH');EXCEPTION WHEN OTHERS THEN denied:=true;END;IF NOT denied THEN RAISE EXCEPTION 'Student edited payment'; END IF;
 INSERT INTO fee_module_checks VALUES('Student dashboard matches all fee types; admin finances and mutations denied to students',true);
 INSERT INTO fee_module_context VALUES(uid,sid,monthly);
END $$;
GRANT SELECT ON fee_module_context TO authenticated;
SET LOCAL ROLE authenticated;
DO $$ DECLARE sid uuid; touched int; BEGIN SELECT c.sid INTO sid FROM fee_module_context c;
 IF EXISTS(SELECT 1 FROM student_fee_accounts a WHERE a.student_id<>sid) OR EXISTS(SELECT 1 FROM student_fee_payments p WHERE p.student_id<>sid) THEN RAISE EXCEPTION 'Student fee RLS leak'; END IF;
 UPDATE student_fee_accounts SET status='WAIVED';GET DIAGNOSTICS touched=ROW_COUNT;IF touched<>0 THEN RAISE EXCEPTION 'Student can alter fees'; END IF;
 PERFORM finance_student_fee_data();
END $$;
RESET ROLE;
INSERT INTO fee_module_checks VALUES('Actual authenticated RLS: own accounts/history readable; fee mutations denied',true);
SELECT * FROM fee_module_checks;
ROLLBACK;
