BEGIN;
CREATE TEMP TABLE review_checks(name text,passed boolean);
CREATE TEMP TABLE review_context(uid uuid,sid uuid,tid uuid,aid uuid,rid uuid);
DO $$
DECLARE staff uuid; uid uuid:=gen_random_uuid(); other_uid uuid:=gen_random_uuid(); sid uuid; c record; subj uuid; qids uuid[]; keys uuid[]; wrong uuid; tid uuid; aid uuid; result jsonb; detail jsonb; payload jsonb; config jsonb; t tests%ROWTYPE; denied boolean; original_stem text; original_explanation text;
BEGIN
 SELECT id INTO staff FROM profiles WHERE role='ADMIN' AND status='ACTIVE' LIMIT 1;
 SELECT * INTO c FROM courses WHERE code='PMA_LONG_COURSE';SELECT id INTO subj FROM subjects WHERE code='INTELLIGENCE_VERBAL';
 SELECT array_agg(id ORDER BY code) INTO qids FROM (SELECT q.id,q.code FROM questions q WHERE q.status='APPROVED' AND q.subject_id=subj AND exam_question_course_eligible(q.id,c.id) AND (SELECT count(*) FROM question_options WHERE question_id=q.id)=4 AND (SELECT count(*) FROM question_options WHERE question_id=q.id AND is_correct)=1 ORDER BY code LIMIT 3)x;
 IF cardinality(qids)<>3 THEN RAISE EXCEPTION 'Approved bank insufficient'; END IF;
 SELECT array_agg(o.id ORDER BY array_position(qids,o.question_id)) INTO keys FROM question_options o WHERE o.question_id=ANY(qids) AND is_correct;
 SELECT id INTO wrong FROM question_options WHERE question_id=qids[2] AND NOT is_correct ORDER BY label LIMIT 1;
 SELECT stem,explanation INTO original_stem,original_explanation FROM questions WHERE id=qids[1];
 INSERT INTO auth.users(id,email) VALUES(uid,uid||'@answer-review-rollback.invalid'),(other_uid,other_uid||'@answer-review-rollback.invalid');
 INSERT INTO students(profile_id,roll_number,father_name,target_force_id,target_course_id) VALUES(uid,'REVIEW-'||uid,'Fixture',c.force_id,c.id) RETURNING id INTO sid;
 INSERT INTO students(profile_id,roll_number,father_name,target_force_id,target_course_id) VALUES(other_uid,'REVIEW-'||other_uid,'Fixture',c.force_id,c.id);
 PERFORM set_config('request.jwt.claim.sub',staff::text,true);PERFORM set_config('request.jwt.claim.role','authenticated',true);
 config:=jsonb_build_object('test',jsonb_build_object('name','Answer review rollback verification','duration_minutes',1,'passing_threshold',50,'show_answer_review',false),'eligibilities',jsonb_build_array(jsonb_build_object('force_id',c.force_id,'course_id',c.id)),'sections',jsonb_build_array(jsonb_build_object('name','Verbal Intelligence','position',1,'question_count',3,'duration_minutes',1,'subject_ids',jsonb_build_array(subj),'question_ids',to_jsonb(qids))));
 t:=save_test_blueprint(config);tid:=t.id;
 PERFORM set_config('request.jwt.claim.sub',uid::text,true);result:=start_test_attempt(tid);aid:=(result->>'attempt_id')::uuid;
 payload:=get_safe_exam_payload(aid);IF payload::text LIKE '%is_correct%' OR payload::text LIKE '%answer_keys%' OR payload::text LIKE '%review_metadata%' THEN RAISE EXCEPTION 'Active exam exposes review'; END IF;
 denied:=false;BEGIN PERFORM get_result_detail(gen_random_uuid());EXCEPTION WHEN OTHERS THEN denied:=true;END;IF NOT denied THEN RAISE EXCEPTION 'Unfinalized review accepted'; END IF;
 INSERT INTO review_checks VALUES('Active exam payload hides keys/explanations; review requires saved finalized result',true);
 PERFORM save_answer(aid,qids[1],keys[1],false);PERFORM save_answer(aid,qids[2],wrong,false);
 result:=submit_test_attempt(aid);detail:=get_result_detail((result->>'result_id')::uuid);
 IF NOT(detail->>'answer_review_enabled')::boolean OR jsonb_array_length(detail#>'{sections,0,questions}')<>3 OR detail#>>'{sections,0,questions,0,status}'<>'correct' OR detail#>>'{sections,0,questions,1,status}'<>'incorrect' OR detail#>>'{sections,0,questions,2,status}'<>'skipped' THEN RAISE EXCEPTION 'Review counts/status mismatch'; END IF;
 IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(detail#>'{sections,0,questions,0,options}') opt WHERE opt->>'id'=keys[1]::text AND (opt->>'is_correct')::boolean) THEN RAISE EXCEPTION 'Correct key missing'; END IF;
 IF detail#>>'{sections,0,questions,1,selected_option_id}'<>wrong::text THEN RAISE EXCEPTION 'Own choice missing'; END IF;
 INSERT INTO review_checks VALUES('Completed owner receives exactly three saved questions, correct/incorrect/skipped states and own choices',true);
 UPDATE questions SET stem='Edited after immutable snapshot',explanation='Edited live explanation' WHERE id=qids[1];
 UPDATE question_options SET is_correct=NOT is_correct WHERE question_id=qids[1] AND id IN(keys[1],(SELECT id FROM question_options WHERE question_id=qids[1] AND NOT is_correct ORDER BY label LIMIT 1));
 PERFORM exam_capture_attempt(aid);
 detail:=get_result_detail((result->>'result_id')::uuid);
 IF detail#>>'{sections,0,questions,0,stem}' IS DISTINCT FROM original_stem OR detail#>>'{sections,0,questions,0,explanation}' IS DISTINCT FROM original_explanation OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements(detail#>'{sections,0,questions,0,options}') opt WHERE opt->>'id'=keys[1]::text AND (opt->>'is_correct')::boolean) THEN RAISE EXCEPTION 'Review used mutable bank'; END IF;
 INSERT INTO review_checks VALUES('Review uses immutable exam text/options/key/explanations after bank edits',true);
 PERFORM set_config('request.jwt.claim.sub',other_uid::text,true);denied:=false;BEGIN PERFORM get_result_detail((result->>'result_id')::uuid);EXCEPTION WHEN OTHERS THEN denied:=true;END;IF NOT denied THEN RAISE EXCEPTION 'Cross-owner review'; END IF;
 INSERT INTO review_checks VALUES('Other student cannot access completed review',true);
 PERFORM set_config('request.jwt.claim.sub',uid::text,true);UPDATE test_attempts SET status='EXPIRED' WHERE id=aid;denied:=false;BEGIN PERFORM get_result_detail((result->>'result_id')::uuid);EXCEPTION WHEN OTHERS THEN denied:=true;END;IF NOT denied THEN RAISE EXCEPTION 'Invalidated result accepted'; END IF;UPDATE test_attempts SET status='SUBMITTED' WHERE id=aid;
 INSERT INTO review_checks VALUES('Invalidated results remain inaccessible',true);
 INSERT INTO review_context VALUES(uid,sid,tid,aid,(result->>'result_id')::uuid);
END $$;
SELECT set_config('request.jwt.claim.sub',(SELECT uid::text FROM review_context),true);
GRANT SELECT ON review_context TO authenticated;
SET LOCAL ROLE authenticated;
DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM exam_attempt_snapshots) THEN RAISE EXCEPTION 'Private snapshot visible'; END IF;
 IF EXISTS(SELECT 1 FROM question_options) THEN RAISE EXCEPTION 'Raw bank keys visible'; END IF;
 IF NOT(get_result_detail((SELECT rid FROM review_context))->>'answer_review_enabled')::boolean THEN RAISE EXCEPTION 'Owner review denied'; END IF;
END $$;
RESET ROLE;
INSERT INTO review_checks VALUES('Actual authenticated RLS hides private snapshot and raw bank while own finalized review works',true);
DO $$ BEGIN IF has_function_privilege('anon','public.get_result_detail(uuid)','EXECUTE') THEN RAISE EXCEPTION 'Anonymous review allowed'; END IF; END $$;
INSERT INTO review_checks VALUES('Anonymous result review denied',true);
SELECT * FROM review_checks;
ROLLBACK;
