BEGIN;
CREATE TEMP TABLE salary_checks(name text,passed boolean,details text);
DO $$
DECLARE staff uuid; teacher_uid uuid; other_uid uuid:=gen_random_uuid(); student_uid uuid; s teacher_salary_payments%ROWTYPE; r jsonb; rows jsonb; denied boolean; base_summary numeric; uid uuid; expense_id uuid;
BEGIN
 SELECT id INTO staff FROM profiles WHERE role='ADMIN' AND status='ACTIVE' LIMIT 1;
 SELECT * INTO s FROM teacher_salary_payments WHERE status='ACTIVE' LIMIT 1;
 IF s.id IS NULL THEN RAISE EXCEPTION 'Existing salary required for rollback verification'; END IF;
 teacher_uid:=s.teacher_profile_id;
 PERFORM set_config('request.jwt.claim.sub',staff::text,true);PERFORM set_config('request.jwt.claim.role','authenticated',true);
 rows:=finance_salary_eligible_teachers(s.salary_year,s.salary_month);
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(rows) t WHERE t->>'id'=teacher_uid::text) THEN RAISE EXCEPTION 'Paid teacher still eligible'; END IF;
 rows:=finance_salary_eligible_teachers(s.salary_year,CASE WHEN s.salary_month=12 THEN 1 ELSE s.salary_month+1 END);
 IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(rows) t WHERE t->>'id'=teacher_uid::text) THEN RAISE EXCEPTION 'Teacher missing from another month'; END IF;
 INSERT INTO salary_checks VALUES('Existing DB teacher excluded only for paid month',true,'Legacy teacher profile loaded even without faculty docket');
 r:=finance_update_salary_payment(s.id,jsonb_build_object('bonus',s.bonus+25,'notes','Rollback salary edit verification'));
 IF (r->>'net_paid')::numeric<>s.net_paid+25 OR (r->>'base_salary')::numeric<>s.base_salary OR (r->>'deduction')::numeric<>s.deduction OR (r->>'updated_at')::timestamptz<=s.updated_at THEN RAISE EXCEPTION 'Partial update or timestamp mismatch'; END IF;
 IF NOT EXISTS(SELECT 1 FROM finance_expenses WHERE id=s.expense_id AND amount=s.net_paid+25 AND description='Rollback salary edit verification') THEN RAISE EXCEPTION 'Linked expense mismatch'; END IF;
 INSERT INTO salary_checks VALUES('Salary partial edit merges old values, updates timestamp and linked expense',true,'Bonus +25; all untouched amounts preserved');
 PERFORM set_config('request.jwt.claim.sub',teacher_uid::text,true);
 rows:=get_my_teacher_salaries(s.salary_year,s.salary_month);
 IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(rows)t WHERE t->>'id'=s.id::text AND (t->>'net_paid')::numeric=s.net_paid+25 AND t->>'notes'='Rollback salary edit verification') THEN RAISE EXCEPTION 'Teacher summary not updated'; END IF;
 denied:=false;BEGIN PERFORM finance_update_salary_payment(s.id,'{}');EXCEPTION WHEN OTHERS THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'Teacher could change salary'; END IF;
 INSERT INTO salary_checks VALUES('Teacher own salary read shows updated details; salary write denied',true,'Backend ownership enforced');
 INSERT INTO auth.users(id,email) VALUES(other_uid,other_uid||'@salary-rollback.invalid');
 UPDATE profiles SET role='TEACHER',status='ACTIVE' WHERE id=other_uid;
 PERFORM set_config('request.jwt.claim.sub',other_uid::text,true);
 IF jsonb_array_length(get_my_teacher_salaries(s.salary_year))<>0 THEN RAISE EXCEPTION 'Another teacher salary exposed'; END IF;
 SELECT profile_id INTO student_uid FROM students LIMIT 1;PERFORM set_config('request.jwt.claim.sub',student_uid::text,true);
 denied:=false;BEGIN PERFORM get_my_teacher_salaries(s.salary_year);EXCEPTION WHEN OTHERS THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'Student could read teacher salary'; END IF;
 INSERT INTO salary_checks VALUES('Other teacher cannot see salary and students denied',true,'No profile ID parameter accepted');
 PERFORM set_config('request.jwt.claim.sub',staff::text,true);
 denied:=false;BEGIN PERFORM record_finance_expense(p_category_code=>'SALARY',p_title=>'Rollback duplicate',p_teacher_id=>teacher_uid,p_salary_month=>s.salary_month,p_salary_year=>s.salary_year,p_salary_payment_type=>'BONUS',p_base_salary=>0,p_bonus=>100,p_deduction=>0);EXCEPTION WHEN OTHERS THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'Duplicate monthly payout accepted'; END IF;
 INSERT INTO salary_checks VALUES('Duplicate monthly payment rejected for every payout type',true,'Unique active teacher/year/month index prevents concurrent duplicates');
 denied:=false;BEGIN UPDATE finance_expenses SET amount=1 WHERE id=s.expense_id;EXCEPTION WHEN OTHERS THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'Expense could diverge from payroll'; END IF;
 r:=void_finance_expense(s.expense_id,'Rollback void verification');
 rows:=finance_salary_eligible_teachers(s.salary_year,s.salary_month);
 IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(rows)t WHERE t->>'id'=teacher_uid::text) OR (SELECT status FROM teacher_salary_payments WHERE id=s.id)<>'VOID' THEN RAISE EXCEPTION 'Void did not release teacher'; END IF;
 INSERT INTO salary_checks VALUES('Expense mismatch rejected; void synchronizes salary and restores eligibility',true,'All financial test writes rolled back');
END $$;
SELECT * FROM salary_checks;
ROLLBACK;
