import { useRef, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import * as Dialog from '@radix-ui/react-dialog';
import { Anchor, Plane, Shield, X, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '@/app/providers';
import { ConfirmDialog } from '@/components/ui/ConfirmDialog';
import { academyDate, attendanceService, attendanceTime, statusLabel, AttendanceRow, AttendanceSection, AttendanceCourse, AttendanceFilters } from '@/services/attendanceService';
import { useAttendanceUpdates } from './useAttendanceUpdates';

const button = 'rounded-lg border px-3 py-2 text-sm font-semibold disabled:opacity-50 disabled:cursor-not-allowed';
const primary = button + ' bg-emerald-700 text-white hover:bg-emerald-800';
const field = 'w-full min-w-0 rounded-lg border bg-white px-3 py-2 text-sm focus:ring-2 focus:ring-emerald-600';
const panel = 'rounded-2xl border bg-white p-4 sm:p-5 space-y-4';
const sections: AttendanceSection[] = ['Army', 'Navy', 'Air Force'];
const icons = { Army: Shield, Navy: Anchor, 'Air Force': Plane };
const queryOptions = { staleTime: 0, refetchInterval: 15000, refetchOnWindowFocus: true, refetchOnReconnect: true };
function State({ error, pending, retry }: { error: Error | null; pending: boolean; retry: () => void }) { return pending ? <p aria-live="polite" className="text-sm text-slate-500">Loading saved attendance…</p> : error ? <div role="alert" className="text-sm text-red-700"><p>{error.message}</p><button className={button} onClick={retry}>Retry</button></div> : null; }
function Badge({ status }: { status: string }) { return <span className={'rounded-md border px-2 py-1 text-xs font-semibold ' + (status === 'PRESENT' ? 'bg-emerald-50 text-emerald-800' : status === 'ABSENT' ? 'bg-red-50 text-red-800' : 'bg-slate-50 text-slate-700')}>{statusLabel(status)}</span>; }
function CourseSection({ course, date, state, onCorrect }: { course: AttendanceCourse; date: string; state?: string; onCorrect: (row: AttendanceRow) => void }) {
 const section = course.section;
 const [roll, setRoll] = useState(''); const [search, setSearch] = useState(''); const [offset, setOffset] = useState(0); const [includeUnmarked, setIncludeUnmarked] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const input = useRef<HTMLInputElement>(null); const cache = useQueryClient(); const { user } = useAuth(); const Icon = icons[section];
 const q = useQuery({ queryKey: ['attendance', 'course', user?.id, date, course.id, search, offset, includeUnmarked], queryFn: () => attendanceService.report({ from: date, to: date, section, course: course.id, search, offset, limit: 20, includeUnmarked }), ...queryOptions });
 async function mark(e: React.FormEvent) { e.preventDefault(); if (busy) return; setBusy(true); setError(''); try { const result = await attendanceService.markCourse(date, course.id, roll); toast.success(result.message); setRoll(''); await cache.invalidateQueries({ queryKey: ['attendance'] }); } catch (e) { setError((e as Error).message); await cache.invalidateQueries({ queryKey: ['attendance'] }); } finally { setBusy(false); requestAnimationFrame(() => input.current?.focus()); } }
 return <section className={panel} aria-label={`${course.name} attendance`}>
  <div className="flex items-center justify-between gap-2"><h2 className="flex items-center gap-2 font-bold text-lg"><Icon className="w-5 h-5 text-emerald-700" />{course.name}</h2><div className="text-xs text-right"><p>Present: {q.data?.totals.present ?? '—'}</p><p>Unmarked: {q.data?.totals.unmarked ?? '—'}</p></div></div>
  <form className="space-y-2" onSubmit={mark}><label htmlFor={`roll-${course.id}`} className="text-sm font-semibold">Roll-number suffix</label><div className="flex min-w-0 items-center rounded-lg border bg-slate-50 focus-within:ring-2 focus-within:ring-emerald-600"><span className="pl-3 pr-1 font-mono text-sm font-semibold whitespace-nowrap" id={`prefix-${course.id}`}>{course.roll_prefix}</span><input id={`roll-${course.id}`} aria-describedby={`prefix-${course.id}`} ref={input} value={roll} onChange={e => setRoll(e.target.value)} placeholder="1" inputMode="numeric" pattern="[0-9]+" autoComplete="off" className="w-full min-w-0 rounded-r-lg bg-white px-2 py-2 text-sm outline-none" disabled={state !== 'OPEN' || busy} /></div><button type="submit" className={primary + ' w-full'} disabled={!roll.trim() || busy || state !== 'OPEN'}>{busy ? 'Saving…' : 'Mark Present'}</button>{state !== 'OPEN' && <p className="text-xs text-slate-500">{state ? `${statusLabel(state)}: ordinary marking is disabled.` : 'Create the daily register to start marking.'}</p>}{error && <p role="alert" className="text-sm text-red-700">{error}</p>}</form>
  <label className="block text-sm">Search saved entries<input aria-label={`${course.name} attendance search`} className={field + ' mt-1'} value={search} onChange={e => { setSearch(e.target.value); setOffset(0); }} /></label>
  <label className="flex gap-2 text-xs items-center"><input type="checkbox" checked={includeUnmarked} onChange={e => { setIncludeUnmarked(e.target.checked); setOffset(0); }} />Include unmarked roster</label>
  <State pending={q.isPending} error={q.error} retry={() => q.refetch()} />
  {!q.isError && q.data && <><div className="space-y-2">{q.data.rows.map(row => <div key={row.student_id} className="rounded-xl border p-3 space-y-2">
   <div className="flex gap-3 items-start">{row.photo_url ? <img src={row.photo_url} alt="" className="w-9 h-9 rounded-full object-cover" /> : <span className="w-9 h-9 rounded-full bg-slate-100 text-slate-600 flex items-center justify-center shrink-0 text-xs font-bold">{row.student_name.split(/\s+/).slice(0, 2).map(x => x[0]).join('')}</span>}<div className="min-w-0 flex-1"><p className="font-semibold text-sm break-words">{row.student_name}</p><p className="text-xs font-mono break-all">{row.roll_number}</p><p className="text-xs text-slate-500">{row.memberships.filter(x => x.course_id === course.id).map(x => x.course_name).join(', ')}</p></div></div>
   <div className="flex items-center justify-between gap-2 flex-wrap"><Badge status={state === 'NON_CLASS' ? 'NON_CLASS' : row.status} /><span className="text-xs">Arrival: {attendanceTime(row.arrival_at)}</span><button className={button} onClick={() => onCorrect(row)}>Correct</button></div>{row.conflict && <p className="text-xs text-red-700">Eligibility conflict — assignment changed after marking.</p>}
  </div>)}{!q.data.rows.length && <p className="text-sm text-slate-500">No matching saved entries.</p>}</div><div className="flex items-center justify-between gap-2 text-xs"><button className={button} disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 20))}>Previous</button><span>{q.data.total ? offset + 1 : 0}–{Math.min(offset + 20, q.data.total)} / {q.data.total}</span><button className={button} disabled={offset + 20 >= q.data.total} onClick={() => setOffset(offset + 20)}>Next</button></div></>}
 </section>;
}
const escapeHtml = (v: unknown) => String(v ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
function csvDownload(rows: unknown[][], name: string) { const csv = rows.map(row => row.map(v => { const text = String(v ?? ''); return '"' + (/^[=+@\-]/.test(text) ? "'" : '') + text.replace(/"/g, '""') + '"'; }).join(',')).join('\r\n'); const url = URL.createObjectURL(new Blob(['\uFEFF', csv], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }
function Reports({ date, chooseDate }: { date: string; chooseDate: (date: string) => void }) {
 const { user } = useAuth(); const [filters, setFilters] = useState<AttendanceFilters>({ from: date.slice(0, 7) + '-01', to: date }); const [offset, setOffset] = useState(0); const [busy, setBusy] = useState(false);
 const q = useQuery({ queryKey: ['attendance', 'report', user?.id, filters, offset], queryFn: () => attendanceService.report({ ...filters, offset }), ...queryOptions });
 const change = (key: keyof AttendanceFilters, value: string) => { setFilters(f => ({ ...f, [key]: value, ...(key === 'section' ? { course: '' } : {}) })); setOffset(0); };
 async function exportRows(print: boolean) { const win = print ? window.open('', '_blank') : null; if (print && !win) { toast.error('Allow popups to print this report.'); return; } setBusy(true); try { const rows: AttendanceRow[] = []; let n = 0; while (true) { const part = await attendanceService.report({ ...filters, offset: n, limit: 200 }); rows.push(...part.rows); n += part.rows.length; if (n >= part.total || !part.rows.length) break; } const headings = ['Date', 'Register', 'Roll number', 'Student', 'Courses / sections', 'Status', 'Arrival (Pakistan time)']; const cells = rows.map(r => [r.attendance_date, statusLabel(r.state), r.roll_number, r.student_name, r.memberships.map(m => `${m.section}: ${m.course_name}`).join('; '), statusLabel(r.state === 'NON_CLASS' ? 'NON_CLASS' : r.status), attendanceTime(r.arrival_at)]); if (win) { win.document.write(`<html><head><title>Attendance ${escapeHtml(filters.from)} to ${escapeHtml(filters.to)}</title><style>body{font:12px Arial;color:#18283B}table{width:100%;border-collapse:collapse}th,td{border:1px solid #DFE6EE;padding:6px;text-align:left}thead{display:table-header-group}</style></head><body><h1>Student Attendance</h1><p>${escapeHtml(filters.from)} to ${escapeHtml(filters.to)} · ${escapeHtml(filters.section || 'All sections')} · Open registers are incomplete.</p><table><thead><tr>${headings.map(h => `<th>${escapeHtml(h)}</th>`).join('')}</tr></thead><tbody>${cells.map(row => `<tr>${row.map(c => `<td>${escapeHtml(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`); win.document.close(); win.focus(); win.print(); } else csvDownload([headings, ...cells], `SFA_Attendance_${filters.from}_${filters.to}.csv`); } catch (e) { win?.close(); toast.error((e as Error).message); } finally { setBusy(false); } }
 return <section className={panel}><h2 className="text-xl font-bold">History & Reports</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-6 gap-3">
  <label className="text-sm">From<input className={field} type="date" value={filters.from} max={academyDate()} onChange={e => change('from', e.target.value)} /></label><label className="text-sm">To<input className={field} type="date" value={filters.to} max={academyDate()} onChange={e => change('to', e.target.value)} /></label>
  <label className="text-sm">Force section<select className={field} value={filters.section || ''} onChange={e => change('section', e.target.value)}><option value="">All sections</option>{sections.map(s => <option key={s}>{s}</option>)}</select></label>
  <label className="text-sm">Course<select className={field} value={filters.course || ''} onChange={e => change('course', e.target.value)}><option value="">All courses</option>{q.data?.courses.filter(c => !filters.section || c.section === filters.section).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
  <label className="text-sm">Name / roll number<input className={field} value={filters.search || ''} onChange={e => change('search', e.target.value)} /></label><label className="text-sm">Status<select className={field} value={filters.status || ''} onChange={e => change('status', e.target.value)}><option value="">All statuses</option>{['PRESENT', 'ABSENT', 'EXCUSED', 'UNMARKED'].map(s => <option key={s} value={s}>{statusLabel(s)}</option>)}</select></label>
 </div><div className="flex flex-wrap gap-2"><button className={button} disabled={busy || q.isError || !q.data} onClick={() => exportRows(false)}>Export CSV (Excel)</button><button className={button} disabled={busy || q.isError || !q.data} onClick={() => exportRows(true)}>Print / Save PDF</button><button className={button} disabled={!q.data || q.isError} onClick={() => csvDownload([['Month', 'Roll number', 'Student', 'Present', 'Absent', 'Excused', 'Percentage'], ...(q.data?.monthly || []).map(r => [r.month, r.roll_number, r.student_name, r.present, r.absent, r.excused, r.percentage])], 'SFA_Attendance_Monthly.csv')}>Export Monthly CSV</button></div>
 <State pending={q.isPending} error={q.error} retry={() => q.refetch()} />{q.data && !q.isError && <>
  <p className="text-sm">Unique students: {q.data.totals.unique_students} � Saved student-days: {q.data.totals.eligible} · Present {q.data.totals.present} · Absent {q.data.totals.absent} · Excused {q.data.totals.excused} · Unmarked {q.data.totals.unmarked} · Official attendance: {q.data.totals.percentage === null ? 'No attendance recorded' : `${q.data.totals.percentage}%`}</p>
  <p className="text-xs text-slate-500">Open registers are incomplete. Official percentages use finalized class days only. Non-class days are excluded.</p>
  <div className="flex flex-wrap gap-2">{q.data.registers.map(r => <button key={r.id} className={button} onClick={() => chooseDate(r.attendance_date)}>{r.attendance_date} · {statusLabel(r.state)}</button>)}{!q.data.registers.length && <p>No registers recorded in this range.</p>}</div>
  <div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{['Date', 'Roll number', 'Student', 'Course / section', 'Status', 'Register', 'Arrival'].map(h => <th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{q.data.rows.map(r => <tr key={r.register_id + r.student_id} className="border-t"><td className="p-2 whitespace-nowrap">{r.attendance_date}</td><td className="p-2 whitespace-nowrap">{r.roll_number}</td><td className="p-2">{r.student_name}</td><td className="p-2">{r.memberships.map(m => `${m.section}: ${m.course_name}`).join(', ')}</td><td className="p-2"><Badge status={r.state === 'NON_CLASS' ? 'NON_CLASS' : r.status} /></td><td className="p-2">{statusLabel(r.state)}</td><td className="p-2">{attendanceTime(r.arrival_at)}</td></tr>)}</tbody></table>{!q.data.rows.length && <p>No matching attendance records.</p>}</div>
  <div className="flex justify-between items-center"><button className={button} disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 50))}>Previous</button><span className="text-sm">{q.data.total ? offset + 1 : 0}–{Math.min(offset + 50, q.data.total)} / {q.data.total}</span><button className={button} disabled={offset + 50 >= q.data.total} onClick={() => setOffset(offset + 50)}>Next</button></div>
  <h3 className="font-bold">Monthly Student Summaries</h3><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{['Month', 'Student / roll', 'Present', 'Absent', 'Excused', 'Percentage'].map(h => <th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{q.data.monthly.map(r => <tr key={r.month + r.student_id} className="border-t"><td className="p-2">{r.month}</td><td className="p-2">{r.student_name} · {r.roll_number}</td><td className="p-2">{r.present}</td><td className="p-2">{r.absent}</td><td className="p-2">{r.excused}</td><td className="p-2">{r.percentage === null ? 'No attendance recorded' : `${r.percentage}%`}</td></tr>)}</tbody></table></div>
 </>}
 </section>;
}
export default function AttendancePage() {
 const { user } = useAuth(); const cache = useQueryClient(); const [date, setDate] = useState(academyDate()); const [history, setHistory] = useState(false); const [dialog, setDialog] = useState<{ action: string; row?: AttendanceRow } | null>(null); const [reason, setReason] = useState(''); const [status, setStatus] = useState('PRESENT'); const [resolve, setResolve] = useState(false); const [busy, setBusy] = useState(false); const [dialogError, setDialogError] = useState('');
 useAttendanceUpdates(); const q = useQuery({ queryKey: ['attendance', 'daily', user?.id, date], queryFn: () => attendanceService.report({ from: date, to: date }), ...queryOptions }); const register = q.data?.registers.find(r => r.attendance_date === date);
 function open(action: string, row?: AttendanceRow) { setReason(''); setResolve(false); setStatus(row?.status || 'PRESENT'); setDialogError(''); setDialog({ action, row }); }
 async function act(action: string, data: Record<string, unknown> = {}) { setBusy(true); setDialogError(''); try { const result = await attendanceService.action(action, date, data); toast.success(result.message); setDialog(null); } catch (e) { setDialogError((e as Error).message); toast.error((e as Error).message); } finally { await cache.invalidateQueries({ queryKey: ['attendance'] }); setBusy(false); } }
 return <div className="staff-page space-y-6 max-w-[1520px] mx-auto"><header className="flex flex-wrap justify-between items-center gap-4"><div><h1 className="text-3xl font-bold">Student Attendance</h1><p className="text-sm text-slate-500 mt-1">Mark daily arrivals by roll number. Times use Asia/Karachi.</p></div><button className={button} onClick={() => setHistory(!history)}>{history ? 'Hide History & Reports' : 'History & Reports'}</button></header>
  <section className={panel}><div className="flex flex-wrap gap-3 items-end"><label className="text-sm font-semibold">Academy date<input aria-label="Academy date" className={field + ' mt-1'} type="date" max={q.data?.today || academyDate()} value={date} onChange={e => { if (e.target.value) { setDate(e.target.value); setDialog(null); } }} /></label><Badge status={register?.state || 'No register recorded'} /><button className={button} onClick={() => q.refetch()} aria-label="Refresh attendance"><RefreshCw className="w-4 h-4" /></button>
   {!register && !q.isPending && !q.isError && <button className={primary} onClick={() => open('CREATE')}>Create Daily Register</button>}
   {register?.state === 'OPEN' && <><button className={button} disabled={busy} onClick={() => act('SYNC')}>Synchronize Roster</button><button className={primary} disabled={busy || q.isError} onClick={() => open('FINALIZE')}>Finalize Attendance</button></>}
   {register && register.state !== 'OPEN' && <button className={button} onClick={() => open('REOPEN')}>Reopen Register</button>}
   {register && register.state !== 'NON_CLASS' && <button className={button} onClick={() => open('NON_CLASS')}>Mark Non-class Day</button>}
  </div><State error={q.error} pending={q.isPending} retry={() => q.refetch()} />{q.data && !q.isError && <><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{(['eligible', 'present', 'absent', 'unmarked'] as const).map(k => <div className="rounded-xl border p-3" key={k}><p className="text-xs uppercase text-slate-500">{k} students</p><p className="text-2xl font-bold">{q.data.totals[k]}</p></div>)}</div><p className="text-xs text-slate-500" title="Each student appears once in overall totals, but can appear in multiple eligible course sections.">Overall totals count unique students; multi-course section totals are not additive.</p>{register?.state === 'NON_CLASS' && <p>Attendance is not required: {register.reason}</p>}{q.data.totals.conflicts > 0 && <p role="alert" className="text-red-700 text-sm">{q.data.totals.conflicts} eligibility conflicts. Restore the saved assignment or explicitly exclude each conflicting entry with a reason before finalizing.</p>}</>}</section>
  <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5 items-start">{!q.isError && q.data?.courses.map(course => <CourseSection key={course.id + date} course={course} date={date} state={q.isError ? undefined : register?.state} onCorrect={row => open('CORRECT', row)} />)}</div>
  {history && <Reports date={date} chooseDate={setDate} />}
  {register && <details className={panel}><summary className="font-semibold cursor-pointer">Recent Audit History (up to 100 changes)</summary><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr><th>Time</th><th>Action</th><th>Change</th><th>Reason</th><th>Acting admin</th></tr></thead><tbody>{q.data?.audit.map(a => <tr className="border-t" key={a.id}><td className="p-2">{attendanceTime(a.occurred_at)}</td><td className="p-2">{a.action}</td><td className="p-2">{a.previous_status} → {a.new_status}</td><td className="p-2">{a.reason || '—'}</td><td className="p-2">{a.actor_name}</td></tr>)}</tbody></table></div></details>}
  <ConfirmDialog isOpen={dialog?.action === 'FINALIZE'} onClose={() => { if (!busy) setDialog(null); }} onConfirm={() => act('FINALIZE', { expectedUnmarked: q.data?.totals.unmarked })} title="Finalize Attendance" description={`${date}: ${q.data?.totals.unmarked ?? 0} eligible unmarked students will become Absent. Present and Excused entries will remain unchanged.`} confirmLabel="Finalize Attendance" isLoading={busy} />
  <Dialog.Root open={!!dialog && dialog.action !== 'FINALIZE'} onOpenChange={v => { if (!v && !busy) setDialog(null); }}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 bg-slate-900/50 z-50" /><Dialog.Content className="academy-management fixed z-50 top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[calc(100%_-_2rem)] max-w-lg max-h-[90vh] overflow-y-auto rounded-2xl border bg-white p-6 space-y-4">
   <div className="flex items-center justify-between"><Dialog.Title className="text-xl font-bold">{dialog?.action === 'CORRECT' ? 'Correct Attendance' : dialog?.action === 'CREATE' ? 'Create Daily Register' : dialog?.action === 'REOPEN' ? 'Reopen Register' : 'Non-class Day'}</Dialog.Title><Dialog.Close disabled={busy} aria-label="Close attendance dialog"><X className="w-5 h-5" /></Dialog.Close></div><Dialog.Description className="text-sm text-slate-500">{date}{dialog?.row ? ` · ${dialog.row.student_name} · ${dialog.row.roll_number}` : ''}</Dialog.Description>
   {dialog?.action === 'CREATE' ? <p className="text-sm">Create an explicit roster from currently active, saved course enrollments eligible on this date. Historical active/archive changes cannot be reconstructed; no attendance will be fabricated for missing days.</p> : <><p className="text-sm">{dialog?.action === 'NON_CLASS' ? 'This date will be excluded from attendance calculations. Existing records will be retained.' : dialog?.action === 'REOPEN' ? 'Reopening preserves all saved statuses; it does not reset absences.' : 'Corrections retain the original arrival time and add a separate audit timestamp.'}</p>
    {dialog?.action === 'CORRECT' && <label className="block text-sm">Status<select aria-label="Attendance status" className={field + ' mt-1'} value={status} onChange={e => setStatus(e.target.value)}>{['PRESENT', 'ABSENT', 'EXCUSED', ...(register?.state === 'OPEN' ? ['UNMARKED'] : [])].map(s => <option key={s} value={s}>{statusLabel(s)}</option>)}</select></label>}
    <label className="block text-sm">Required reason<textarea aria-label="Attendance correction reason" className={field + ' mt-1'} value={reason} onChange={e => setReason(e.target.value)} required /></label>
    {dialog?.action === 'NON_CLASS' && <label className="flex gap-2 text-sm"><input type="checkbox" checked={resolve} onChange={e => setResolve(e.target.checked)} />Explicitly retain recorded attendance and exclude this date from calculations.</label>}
    {dialog?.row?.conflict && <label className="flex gap-2 text-sm"><input type="checkbox" checked={resolve} onChange={e => setResolve(e.target.checked)} />Resolve assignment conflict by excluding this student from this roster; retain their record.</label>}
   </>}{dialogError && <p role="alert" className="text-sm text-red-700">{dialogError}</p>}<div className="flex justify-end gap-2"><Dialog.Close className={button} disabled={busy}>Cancel</Dialog.Close><button className={primary} disabled={busy || (dialog?.action !== 'CREATE' && !reason.trim())} onClick={() => dialog && act(dialog.row?.conflict && resolve ? 'RESOLVE_CONFLICT' : dialog.action, { reason, status, studentId: dialog.row?.student_id, resolveRecorded: resolve, historicalConfirmed: true })}>{busy ? 'Saving…' : dialog?.action === 'CREATE' ? 'Create Daily Register' : 'Save Attendance Change'}</button></div>
  </Dialog.Content></Dialog.Portal></Dialog.Root>
 </div>;
}
