import { Question } from '@/types';

export const mockQuestions: Question[] = [
  {
    id: 'q-001',
    code: 'INT-V-0101',
    subject: 'INTELLIGENCE_VERBAL',
    branch: 'TRI_SERVICE',
    stem: 'If RADAR is coded as 18-1-4-1-18, what is the code for SONAR?',
    options: [
      { id: 'opt-a', label: 'A', text: '19-15-14-1-18' },
      { id: 'opt-b', label: 'B', text: '18-14-1-15-19' },
      { id: 'opt-c', label: 'C', text: '19-14-15-1-18' },
      { id: 'opt-d', label: 'D', text: '20-15-14-1-19' },
    ],
    correctOptionId: 'opt-a',
    explanation: 'Each letter corresponds directly to its alphabetical position: S=19, O=15, N=14, A=1, R=18.',
    difficulty: 'EASY',
    timeLimitSeconds: 45,
    status: 'APPROVED',
    authorName: 'Maj. (R) Tariq Niazi',
    tags: ['Coding-Decoding', 'Verbal Intelligence'],
    updatedAt: '2026-02-18',
  },
  {
    id: 'q-002',
    code: 'INT-V-0102',
    subject: 'INTELLIGENCE_VERBAL',
    branch: 'TRI_SERVICE',
    stem: 'Which word does NOT belong with the others: Frigate, Destroyer, Corvette, Artillery, Submarine?',
    options: [
      { id: 'opt-a', label: 'A', text: 'Frigate' },
      { id: 'opt-b', label: 'B', text: 'Destroyer' },
      { id: 'opt-c', label: 'C', text: 'Artillery' },
      { id: 'opt-d', label: 'D', text: 'Corvette' },
    ],
    correctOptionId: 'opt-c',
    explanation: 'Frigate, Destroyer, Corvette, and Submarine are naval combat vessels. Artillery is a land-based combat arm.',
    difficulty: 'EASY',
    timeLimitSeconds: 30,
    status: 'APPROVED',
    authorName: 'Sqn. Ldr. (R) Arshad',
    tags: ['Classification', 'Odd One Out'],
    updatedAt: '2026-02-19',
  },
  {
    id: 'q-003',
    code: 'INT-NV-0201',
    subject: 'INTELLIGENCE_NON_VERBAL',
    branch: 'TRI_SERVICE',
    stem: 'In an analog dial sequence, a pointer rotates 45 degrees clockwise in step 1, 90 degrees clockwise in step 2, and 135 degrees in step 3. How many degrees must it rotate in step 4?',
    options: [
      { id: 'opt-a', label: 'A', text: '150 degrees clockwise' },
      { id: 'opt-b', label: 'B', text: '180 degrees clockwise' },
      { id: 'opt-c', label: 'C', text: '225 degrees clockwise' },
      { id: 'opt-d', label: 'D', text: '270 degrees clockwise' },
    ],
    correctOptionId: 'opt-b',
    explanation: 'The progression adds 45 degrees at each step: 45, 45+45=90, 90+45=135, 135+45=180 degrees.',
    difficulty: 'MEDIUM',
    timeLimitSeconds: 40,
    status: 'APPROVED',
    authorName: 'Lt. Cdr. (R) Haroon',
    tags: ['Angular Rotation', 'Matrix Reasoning'],
    updatedAt: '2026-02-20',
  },
  {
    id: 'q-004',
    code: 'ACAD-PHY-0301',
    subject: 'ACADEMIC_PHYSICS',
    branch: 'PAKISTAN_AIR_FORCE',
    stem: 'A projectile is launched from ground level at an angle of 45 degrees with an initial velocity of 20 m/s. Assuming g = 9.8 m/s^2 and neglecting air resistance, what is its maximum theoretical horizontal range?',
    options: [
      { id: 'opt-a', label: 'A', text: '20.4 meters' },
      { id: 'opt-b', label: 'B', text: '40.8 meters' },
      { id: 'opt-c', label: 'C', text: '61.2 meters' },
      { id: 'opt-d', label: 'D', text: '81.6 meters' },
    ],
    correctOptionId: 'opt-b',
    explanation: 'Horizontal range R = (v^2 * sin(2*theta)) / g. For theta = 45 deg, sin(90) = 1. R = (20^2) / 9.8 = 400 / 9.8 = 40.82 meters.',
    difficulty: 'MEDIUM',
    timeLimitSeconds: 60,
    status: 'APPROVED',
    authorName: 'Prof. Masood Alam',
    tags: ['Kinematics', 'Projectile Motion'],
    updatedAt: '2026-02-22',
  },
  {
    id: 'q-005',
    code: 'ACAD-MATH-0401',
    subject: 'ACADEMIC_MATH',
    branch: 'PAKISTAN_ARMY',
    stem: 'Evaluate the limit as x approaches 0 of sin(5x) / (3x):',
    options: [
      { id: 'opt-a', label: 'A', text: '1' },
      { id: 'opt-b', label: 'B', text: '3/5' },
      { id: 'opt-c', label: 'C', text: '5/3' },
      { id: 'opt-d', label: 'D', text: 'Undefined' },
    ],
    correctOptionId: 'opt-c',
    explanation: 'Using the fundamental limit lim (x->0) [sin(ax)/(bx)] = a/b, we have 5/3.',
    difficulty: 'EASY',
    timeLimitSeconds: 45,
    status: 'APPROVED',
    authorName: 'Prof. Masood Alam',
    tags: ['Calculus', 'Limits'],
    updatedAt: '2026-02-23',
  },
  {
    id: 'q-006',
    code: 'ACAD-ENG-0501',
    subject: 'ACADEMIC_ENGLISH',
    branch: 'TRI_SERVICE',
    stem: 'Choose the correct preposition: The commanding officer insisted ________ maintaining strict radio silence during the sortie.',
    options: [
      { id: 'opt-a', label: 'A', text: 'for' },
      { id: 'opt-b', label: 'B', text: 'on' },
      { id: 'opt-c', label: 'C', text: 'at' },
      { id: 'opt-d', label: 'D', text: 'over' },
    ],
    correctOptionId: 'opt-b',
    explanation: 'The verb "insist" takes the fixed preposition "on" (or "upon").',
    difficulty: 'EASY',
    timeLimitSeconds: 25,
    status: 'APPROVED',
    authorName: 'Capt. (R) Noman',
    tags: ['Prepositions', 'English Grammar'],
    updatedAt: '2026-02-24',
  },
];
