import { TerminalWorkstation } from '@/types';

export const mockTerminals: TerminalWorkstation[] = [
  {
    id: 'term-01',
    terminalCode: 'WS-CBT-01',
    ipAddress: '192.168.10.101',
    status: 'ACTIVE_EXAM',
    currentCadet: {
      rollNumber: 'PMA-2601',
      name: 'Hamza Tariq',
      branch: 'PAKISTAN_ARMY',
    },
    testTitle: '154 PMA Long Course Initial Test',
    currentQuestion: 42,
    totalQuestions: 100,
    timeRemainingSeconds: 1980,
    answeredCount: 41,
    networkLatencyMs: 4,
    anomalyDetected: false,
    lockStatus: false,
  },
  {
    id: 'term-02',
    terminalCode: 'WS-CBT-02',
    ipAddress: '192.168.10.102',
    status: 'ACTIVE_EXAM',
    currentCadet: {
      rollNumber: 'PAF-4402',
      name: 'Shahmeer Khan',
      branch: 'PAKISTAN_AIR_FORCE',
    },
    testTitle: '158 GDP Comprehensive Exam',
    currentQuestion: 68,
    totalQuestions: 100,
    timeRemainingSeconds: 1420,
    answeredCount: 67,
    networkLatencyMs: 6,
    anomalyDetected: false,
    lockStatus: false,
  },
  {
    id: 'term-03',
    terminalCode: 'WS-CBT-03',
    ipAddress: '192.168.10.103',
    status: 'ANOMALY',
    currentCadet: {
      rollNumber: 'PNC-1108',
      name: 'Bilal Ahmed',
      branch: 'PAKISTAN_NAVY',
    },
    testTitle: 'PN Cadet 2026-A Entry Exam',
    currentQuestion: 15,
    totalQuestions: 80,
    timeRemainingSeconds: 2400,
    answeredCount: 14,
    networkLatencyMs: 142,
    anomalyDetected: true,
    anomalyMessage: 'Multiple window switch events detected (Alt-Tab threshold exceeded)',
    lockStatus: true,
  },
  {
    id: 'term-04',
    terminalCode: 'WS-CBT-04',
    ipAddress: '192.168.10.104',
    status: 'ONLINE',
    currentCadet: null,
    testTitle: null,
    currentQuestion: 0,
    totalQuestions: 0,
    timeRemainingSeconds: 0,
    answeredCount: 0,
    networkLatencyMs: 3,
    anomalyDetected: false,
    lockStatus: false,
  },
];
