import { TestBlueprint } from '@/types';

export const mockTests: TestBlueprint[] = [
  {
    id: '60000000-0000-0000-0000-000000000001',
    code: 'TEST-PMA-154',
    title: '154 PMA Long Course Initial Screening Examination',
    branch: 'PAKISTAN_ARMY',
    courseTarget: '154 PMA Long Course',
    totalQuestions: 45,
    durationMinutes: 65,
    passingScorePercent: 60,
    negativeMarking: false,
    shuffleQuestions: true,
    shuffleOptions: true,
    status: 'ACTIVE',
    sections: [
      {
        id: 'sec-01',
        title: 'Verbal Intelligence',
        subject: 'INTELLIGENCE_VERBAL',
        questionCount: 20,
        timeLimitMinutes: 25,
      },
      {
        id: 'sec-02',
        title: 'Non-Verbal Intelligence',
        subject: 'INTELLIGENCE_NON_VERBAL',
        questionCount: 15,
        timeLimitMinutes: 20,
      },
      {
        id: 'sec-03',
        title: 'Academic Mathematics & General Knowledge',
        subject: 'ACADEMIC_MATH',
        questionCount: 10,
        timeLimitMinutes: 20,
      },
    ],
  },
  {
    id: '60000000-0000-0000-0000-000000000002',
    code: 'TEST-PAF-158',
    title: '158 GDP / CAE Aircrew Comprehensive Evaluation',
    branch: 'PAKISTAN_AIR_FORCE',
    courseTarget: '158 GDP Officer Cadre',
    totalQuestions: 50,
    durationMinutes: 70,
    passingScorePercent: 70,
    negativeMarking: true,
    shuffleQuestions: true,
    shuffleOptions: true,
    status: 'ACTIVE',
    sections: [
      {
        id: 'sec-paf-01',
        title: 'Air Force Intelligence Battery',
        subject: 'INTELLIGENCE_VERBAL',
        questionCount: 20,
        timeLimitMinutes: 25,
      },
      {
        id: 'sec-paf-02',
        title: 'Physics & Flight Dynamics',
        subject: 'ACADEMIC_PHYSICS',
        questionCount: 15,
        timeLimitMinutes: 25,
      },
      {
        id: 'sec-paf-03',
        title: 'Aviation English Comprehension',
        subject: 'ACADEMIC_ENGLISH',
        questionCount: 15,
        timeLimitMinutes: 20,
      },
    ],
  },
  {
    id: '60000000-0000-0000-0000-000000000003',
    code: 'TEST-PN-2026',
    title: 'Pakistan Navy Officer Cadet Entrance Test 2026-A',
    branch: 'PAKISTAN_NAVY',
    courseTarget: 'PN Cadet 2026-A',
    totalQuestions: 40,
    durationMinutes: 60,
    passingScorePercent: 65,
    negativeMarking: false,
    shuffleQuestions: false,
    shuffleOptions: true,
    status: 'ACTIVE',
    sections: [
      {
        id: 'sec-pn-01',
        title: 'Naval Intelligence & Spatial Orientation',
        subject: 'INTELLIGENCE_NON_VERBAL',
        questionCount: 20,
        timeLimitMinutes: 30,
      },
      {
        id: 'sec-pn-02',
        title: 'General Science & Mathematics',
        subject: 'ACADEMIC_MATH',
        questionCount: 20,
        timeLimitMinutes: 30,
      },
    ],
  },
];
