-- Persist the existing educational practice content separately from examination questions.
-- These are explicitly unscored orientation questions, never attempts/results/statistics.
BEGIN;
CREATE TABLE public.portal_practice_questions(code text PRIMARY KEY,subject_id uuid NOT NULL REFERENCES subjects(id),content jsonb NOT NULL);
ALTER TABLE portal_practice_questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY practice_staff ON portal_practice_questions FOR ALL TO authenticated USING(is_admin() OR is_teacher()) WITH CHECK(is_admin() OR is_teacher());
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-VRB-01',id,'{"id":"fam-v-01","code":"DEMO-VRB-01","stem":"If SOLDIER is coded as 19-15-12-4-9-5-18, what is the code for BRAVO?","stem_image_url":null,"explanation":"Each alphabet letter is mapped directly to its 1-indexed alphabetical position: B=2, R=18, A=1, V=22, O=15.","subject_name":"Verbal Intelligence","options":[{"id":"opt-v1-a","label":"A","text":"2-18-1-22-15","image_url":null,"is_correct":true},{"id":"opt-v1-b","label":"B","text":"2-17-1-21-14","image_url":null,"is_correct":false},{"id":"opt-v1-c","label":"C","text":"1-18-2-22-15","image_url":null,"is_correct":false},{"id":"opt-v1-d","label":"D","text":"2-19-1-23-16","image_url":null,"is_correct":false}]}'::jsonb FROM subjects WHERE code='INTELLIGENCE_VERBAL' ON CONFLICT DO NOTHING;
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-VRB-02',id,'{"id":"fam-v-02","code":"DEMO-VRB-02","stem":"Which word does NOT belong with the others in the military hierarchy: General, Admiral, Colonel, Brigade?","stem_image_url":null,"explanation":"General, Admiral, and Colonel are officer ranks; Brigade is a tactical military formation/unit, not a personal rank.","subject_name":"Verbal Intelligence","options":[{"id":"opt-v2-a","label":"A","text":"General","image_url":null,"is_correct":false},{"id":"opt-v2-b","label":"B","text":"Admiral","image_url":null,"is_correct":false},{"id":"opt-v2-c","label":"C","text":"Colonel","image_url":null,"is_correct":false},{"id":"opt-v2-d","label":"D","text":"Brigade","image_url":null,"is_correct":true}]}'::jsonb FROM subjects WHERE code='INTELLIGENCE_VERBAL' ON CONFLICT DO NOTHING;
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-VRB-03',id,'{"id":"fam-v-03","code":"DEMO-VRB-03","stem":"Compass is to Direction as Chronometer is to:","stem_image_url":null,"explanation":"A compass is an instrument used to determine direction, while a chronometer is an instrument designed to measure precise time.","subject_name":"Verbal Intelligence","options":[{"id":"opt-v3-a","label":"A","text":"Altitude","image_url":null,"is_correct":false},{"id":"opt-v3-b","label":"B","text":"Time","image_url":null,"is_correct":true},{"id":"opt-v3-c","label":"C","text":"Pressure","image_url":null,"is_correct":false},{"id":"opt-v3-d","label":"D","text":"Speed","image_url":null,"is_correct":false}]}'::jsonb FROM subjects WHERE code='INTELLIGENCE_VERBAL' ON CONFLICT DO NOTHING;
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-VRB-04',id,'{"id":"fam-v-04","code":"DEMO-VRB-04","stem":"Complete the numeric series: 3, 6, 12, 24, 48, (___)?","stem_image_url":null,"explanation":"Each subsequent term is multiplied by 2 (geometric progression): 48 × 2 = 96.","subject_name":"Verbal Intelligence","options":[{"id":"opt-v4-a","label":"A","text":"72","image_url":null,"is_correct":false},{"id":"opt-v4-b","label":"B","text":"84","image_url":null,"is_correct":false},{"id":"opt-v4-c","label":"C","text":"96","image_url":null,"is_correct":true},{"id":"opt-v4-d","label":"D","text":"108","image_url":null,"is_correct":false}]}'::jsonb FROM subjects WHERE code='INTELLIGENCE_VERBAL' ON CONFLICT DO NOTHING;
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-NVR-01',id,'{"id":"fam-nv-01","code":"DEMO-NVR-01","stem":"In an analog radar display sequence, a target vector rotates 45° clockwise, then 90° clockwise, then 135° clockwise. By how many degrees will it rotate in the 4th step?","stem_image_url":null,"explanation":"The angular rotation increases by an increment of 45° at each phase: 45° → 90° (+45°) → 135° (+45°) → 180° (+45°).","subject_name":"Non-Verbal Intelligence","options":[{"id":"opt-nv1-a","label":"A","text":"150° clockwise","image_url":null,"is_correct":false},{"id":"opt-nv1-b","label":"B","text":"180° clockwise","image_url":null,"is_correct":true},{"id":"opt-nv1-c","label":"C","text":"210° clockwise","image_url":null,"is_correct":false},{"id":"opt-nv1-d","label":"D","text":"225° clockwise","image_url":null,"is_correct":false}]}'::jsonb FROM subjects WHERE code='INTELLIGENCE_NON_VERBAL' ON CONFLICT DO NOTHING;
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-NVR-02',id,'{"id":"fam-nv-02","code":"DEMO-NVR-02","stem":"If a solid square transforms into 4 equal quadrants, and a solid triangle transforms into 3 equal parts, what shape transforms into 5 equal triangular sectors?","stem_image_url":null,"explanation":"A regular polygon divided from its centroid produces identical triangular sectors corresponding to its number of vertices (Pentagon = 5).","subject_name":"Non-Verbal Intelligence","options":[{"id":"opt-nv2-a","label":"A","text":"Hexagon","image_url":null,"is_correct":false},{"id":"opt-nv2-b","label":"B","text":"Pentagon","image_url":null,"is_correct":true},{"id":"opt-nv2-c","label":"C","text":"Octagon","image_url":null,"is_correct":false},{"id":"opt-nv2-d","label":"D","text":"Rhombus","image_url":null,"is_correct":false}]}'::jsonb FROM subjects WHERE code='INTELLIGENCE_NON_VERBAL' ON CONFLICT DO NOTHING;
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-NVR-03',id,'{"id":"fam-nv-03","code":"DEMO-NVR-03","stem":"Identify the spatial mirror reflection of arrow [ → ]: across a vertical axis, it becomes [ ← ]. Across a horizontal axis, what does arrow [ ↑ ] become?","stem_image_url":null,"explanation":"Reflection across a horizontal baseline inverts the vertical direction: upwards [ ↑ ] inverts to downwards [ ↓ ].","subject_name":"Non-Verbal Intelligence","options":[{"id":"opt-nv3-a","label":"A","text":"Arrow pointing Downwards [ ↓ ]","image_url":null,"is_correct":true},{"id":"opt-nv3-b","label":"B","text":"Arrow pointing Rightwards [ → ]","image_url":null,"is_correct":false},{"id":"opt-nv3-c","label":"C","text":"Arrow pointing Leftwards [ ← ]","image_url":null,"is_correct":false},{"id":"opt-nv3-d","label":"D","text":"Arrow pointing Diagonal [ ↗ ]","image_url":null,"is_correct":false}]}'::jsonb FROM subjects WHERE code='INTELLIGENCE_NON_VERBAL' ON CONFLICT DO NOTHING;
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-MTH-01',id,'{"id":"fam-m-01","code":"DEMO-MTH-01","stem":"Evaluate the basic algebraic expression: If 4x + 8 = 32, what is the value of 2x - 3?","stem_image_url":null,"explanation":"4x = 32 - 8 = 24 => x = 6. Substituting into 2x - 3 gives 2(6) - 3 = 12 - 3 = 9.","subject_name":"Academic Mathematics","options":[{"id":"opt-m1-a","label":"A","text":"7","image_url":null,"is_correct":false},{"id":"opt-m1-b","label":"B","text":"9","image_url":null,"is_correct":true},{"id":"opt-m1-c","label":"C","text":"11","image_url":null,"is_correct":false},{"id":"opt-m1-d","label":"D","text":"13","image_url":null,"is_correct":false}]}'::jsonb FROM subjects WHERE code='ACADEMIC_MATH' ON CONFLICT DO NOTHING;
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-MTH-02',id,'{"id":"fam-m-02","code":"DEMO-MTH-02","stem":"What is the sum of interior angles in any convex planar quadrilateral?","stem_image_url":null,"explanation":"The sum of interior angles of an n-sided polygon is (n - 2) × 180°. For n=4, (4 - 2) × 180° = 360°.","subject_name":"Academic Mathematics","options":[{"id":"opt-m2-a","label":"A","text":"180°","image_url":null,"is_correct":false},{"id":"opt-m2-b","label":"B","text":"270°","image_url":null,"is_correct":false},{"id":"opt-m2-c","label":"C","text":"360°","image_url":null,"is_correct":true},{"id":"opt-m2-d","label":"D","text":"540°","image_url":null,"is_correct":false}]}'::jsonb FROM subjects WHERE code='ACADEMIC_MATH' ON CONFLICT DO NOTHING;
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-PHY-01',id,'{"id":"fam-p-01","code":"DEMO-PHY-01","stem":"According to Newton’s Second Law of Motion, acceleration of an aircraft is directly proportional to:","stem_image_url":null,"explanation":"F = ma => a = F/m. Acceleration is directly proportional to net resultant force and inversely proportional to mass.","subject_name":"Academic Physics","options":[{"id":"opt-p1-a","label":"A","text":"Net external force acting upon it","image_url":null,"is_correct":true},{"id":"opt-p1-b","label":"B","text":"Total air density","image_url":null,"is_correct":false},{"id":"opt-p1-c","label":"C","text":"Total flight altitude","image_url":null,"is_correct":false},{"id":"opt-p1-d","label":"D","text":"Aircraft empty weight","image_url":null,"is_correct":false}]}'::jsonb FROM subjects WHERE code='ACADEMIC_PHYSICS' ON CONFLICT DO NOTHING;
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-PHY-02',id,'{"id":"fam-p-02","code":"DEMO-PHY-02","stem":"Which SI unit is used to measure electric capacitance in communications systems?","stem_image_url":null,"explanation":"The SI unit of electrical capacitance is the Farad (F). Henry is inductance, Ohm is resistance, and Tesla is magnetic flux density.","subject_name":"Academic Physics","options":[{"id":"opt-p2-a","label":"A","text":"Henry","image_url":null,"is_correct":false},{"id":"opt-p2-b","label":"B","text":"Ohm","image_url":null,"is_correct":false},{"id":"opt-p2-c","label":"C","text":"Farad","image_url":null,"is_correct":true},{"id":"opt-p2-d","label":"D","text":"Tesla","image_url":null,"is_correct":false}]}'::jsonb FROM subjects WHERE code='ACADEMIC_PHYSICS' ON CONFLICT DO NOTHING;
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-ENG-01',id,'{"id":"fam-e-01","code":"DEMO-ENG-01","stem":"Choose the correct preposition: The cadet platoon was congratulated ________ their outstanding drill performance.","stem_image_url":null,"explanation":"The verb \"congratulate\" takes the fixed dependent preposition \"on\" (e.g., congratulate someone on an achievement).","subject_name":"Academic English","options":[{"id":"opt-e1-a","label":"A","text":"for","image_url":null,"is_correct":false},{"id":"opt-e1-b","label":"B","text":"on","image_url":null,"is_correct":true},{"id":"opt-e1-c","label":"C","text":"at","image_url":null,"is_correct":false},{"id":"opt-e1-d","label":"D","text":"with","image_url":null,"is_correct":false}]}'::jsonb FROM subjects WHERE code='ACADEMIC_ENGLISH' ON CONFLICT DO NOTHING;
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-BIO-01',id,'{"id":"fam-b-01","code":"DEMO-BIO-01","stem":"Which organelle is recognized as the primary site of cellular ATP synthesis in aerobic respiration?","stem_image_url":null,"explanation":"Mitochondria are the powerhouses of eukaryotic cells, generating the majority of cellular adenosine triphosphate (ATP).","subject_name":"Academic Biology","options":[{"id":"opt-b1-a","label":"A","text":"Mitochondria","image_url":null,"is_correct":true},{"id":"opt-b1-b","label":"B","text":"Ribosome","image_url":null,"is_correct":false},{"id":"opt-b1-c","label":"C","text":"Golgi Apparatus","image_url":null,"is_correct":false},{"id":"opt-b1-d","label":"D","text":"Endoplasmic Reticulum","image_url":null,"is_correct":false}]}'::jsonb FROM subjects WHERE code='ACADEMIC_BIOLOGY' ON CONFLICT DO NOTHING;
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-CHM-01',id,'{"id":"fam-c-01","code":"DEMO-CHM-01","stem":"What is the oxidation state of sulfur in sulfuric acid (H2SO4)?","stem_image_url":null,"explanation":"In H2SO4: 2(+1) + S + 4(-2) = 0 => +2 + S - 8 = 0 => S = +6.","subject_name":"Academic Chemistry","options":[{"id":"opt-c1-a","label":"A","text":"+4","image_url":null,"is_correct":false},{"id":"opt-c1-b","label":"B","text":"+6","image_url":null,"is_correct":true},{"id":"opt-c1-c","label":"C","text":"+2","image_url":null,"is_correct":false},{"id":"opt-c1-d","label":"D","text":"-2","image_url":null,"is_correct":false}]}'::jsonb FROM subjects WHERE code='ACADEMIC_CHEMISTRY' ON CONFLICT DO NOTHING;
INSERT INTO portal_practice_questions(code,subject_id,content) SELECT 'DEMO-GEN-01',id,'{"id":"fam-gk-01","code":"DEMO-GEN-01","stem":"What is the highest military gallantry award in the Pakistan Armed Forces?","stem_image_url":null,"explanation":"Nishan-e-Haider (Sign of the Lion) is Pakistan’s highest military valor award, presented posthumously for extraordinary acts of heroism.","subject_name":"General Knowledge","options":[{"id":"opt-gk1-a","label":"A","text":"Hilal-e-Jurat","image_url":null,"is_correct":false},{"id":"opt-gk1-b","label":"B","text":"Sitara-e-Basalat","image_url":null,"is_correct":false},{"id":"opt-gk1-c","label":"C","text":"Nishan-e-Haider","image_url":null,"is_correct":true},{"id":"opt-gk1-d","label":"D","text":"Tamgha-e-Diffa","image_url":null,"is_correct":false}]}'::jsonb FROM subjects WHERE code='GENERAL_KNOWLEDGE' ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION public.get_familiarization_payload(p_test_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE sid uuid:=portal_student_id(); payload jsonb;
BEGIN
 IF NOT EXISTS(SELECT 1 FROM portal_pending(sid) WHERE id=p_test_id) THEN RAISE EXCEPTION 'No eligible pending assignment'; END IF;
 WITH relevant_subjects AS (
 SELECT subject_id FROM test_sections WHERE test_id=p_test_id AND question_count>0 AND subject_id IS NOT NULL
 UNION SELECT q.subject_id FROM test_sections ts JOIN test_section_questions tq ON tq.test_section_id=ts.id JOIN questions q ON q.id=tq.question_id WHERE ts.test_id=p_test_id AND ts.question_count>0
 ), available AS(SELECT p.content,p.subject_id,p.code,row_number() OVER(PARTITION BY p.subject_id ORDER BY p.code) AS n
 FROM portal_practice_questions p JOIN relevant_subjects s ON s.subject_id=p.subject_id),chosen AS(SELECT * FROM available ORDER BY n,subject_id,code LIMIT 5)
 SELECT jsonb_build_object('test_id',p_test_id,'test_name',(SELECT name FROM tests WHERE id=p_test_id),'duration_seconds',60,
 'question_count',count(*),'is_practice_mode',true,'questions',coalesce(jsonb_agg(content ORDER BY n,subject_id,code),'[]')) INTO payload FROM chosen;
 IF (payload->>'question_count')::integer<>5 THEN RAISE EXCEPTION 'Not enough published orientation questions for this test. Contact your instructor.'; END IF;
 RETURN payload;
END $$;
CREATE TABLE public.familiarization_completions(student_id uuid NOT NULL REFERENCES students(id) ON DELETE CASCADE,test_id uuid NOT NULL REFERENCES tests(id),completed_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(student_id,test_id));
ALTER TABLE familiarization_completions ENABLE ROW LEVEL SECURITY;
CREATE POLICY familiarization_read ON familiarization_completions FOR SELECT TO authenticated USING(is_admin() OR is_teacher() OR student_id IN(SELECT id FROM students WHERE profile_id=auth.uid()));
CREATE OR REPLACE FUNCTION public.record_familiarization_completion(p_test_id uuid) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE sid uuid:=portal_student_id();
BEGIN
 IF NOT EXISTS(SELECT 1 FROM portal_pending(sid) WHERE id=p_test_id) THEN RAISE EXCEPTION 'No eligible pending assignment'; END IF;
 INSERT INTO familiarization_completions(student_id,test_id) VALUES(sid,p_test_id) ON CONFLICT(student_id,test_id) DO UPDATE SET completed_at=now();
 RETURN true;
END $$;
CREATE OR REPLACE FUNCTION public.is_familiarization_completed(p_test_id uuid) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE sid uuid:=portal_student_id();
BEGIN RETURN EXISTS(SELECT 1 FROM familiarization_completions WHERE student_id=sid AND test_id=p_test_id); END $$;
REVOKE ALL ON FUNCTION get_familiarization_payload(uuid),record_familiarization_completion(uuid),is_familiarization_completed(uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION get_familiarization_payload(uuid),record_familiarization_completion(uuid),is_familiarization_completed(uuid) TO authenticated;
NOTIFY pgrst,'reload schema';
COMMIT;
